DECLARE
  
  CURSOR TEST_EMP IS 
    SELECT *
    FROM EMPLOYEE
    WHERE DNO = &ENTER_DEPARTMENT_NO;
    
/*F_NAME EMPLOYEE.FNAME%TYPE;
L_NAME FNAME%TYPE;
vSALARY EMPLOYEE.SALARY%TYPE
D_NO EMPLOYEE.DNO%TYPE */

EMPREC EMPLOYEE%ROWTYPE;

BEGIN

OPEN TEST_EMP;

LOOP

FETCH TEST_EMP INTO EMPREC;
EXIT WHEN TEST_EMP%NOTFOUND;

  DBMS_OUTPUT.PUT_LINE (EMPREC.FNAME || ' EARNS $' || EMPREC.SALARY);

END LOOP;

CLOSE TEST_EMP;

EXCEPTION

  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('INVALID ENTRY');

END;

-- TO DISPLAY THE COMPLETE TABLE UNCOMMENT THE FOLLOWING SELECT QUERY
/*
SELECT * FROM EMPLOYEE
ORDER BY DNO;
*/