SET SERVEROUTPUT ON;

DECLARE

F_NAME EMPLOYEE.FNAME%TYPE;
V_SALARY EMPLOYEE.SALARY%TYPE;

BEGIN

SELECT FNAME, SALARY INTO 
F_NAME, V_SALARY 
FROM EMPLOYEE
WHERE SSN = &ENTER_SSN;

DBMS_OUTPUT.PUT_LINE (' SALARY OF THE EMPLYEE ' || F_NAME  || ' IS ' || V_SALARY );

EXCEPTION

  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE ('INVALID SSN');
    
END;